version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    command:
      - 'php'
      - '-S'
      - '[::]:${ADMINER_PORT}'
      - '-t'
      - '/var/www/html'
    depends_on:
      - db

  backend:
    image: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .backend.env
      - .env
    command: bash -c "alembic upgrade head && gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:443"
    depends_on:
      - db

  frontend:
    image: frontend
    restart: always
    build:
      args:
        - REACT_APP_SERVER_PROTOCOL=http
        - REACT_APP_SERVER_HOST=${HOST}
        - REACT_APP_SERVER_PORT=${BACKEND_PORT}
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "serve -s build"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - frontend
